server:
  port: 8080

spring.h2.console:
  enabled: true
  path: /h2-console

spring.jpa.show-sql: true

security:
  oauth2:
    client:
      client-id: foo
      client-secret: bar
      authorized-grant-types: password
    authorization:
      check-token-access: isAuthenticated()
#      token-key-access: isAuthenticated()