server:
  port: 8081

spring.h2.console:
  enabled: true
  path: /h2-console

security:
  oauth2:
    client:
      client-id: foo
      client-secret: bar
    resource:
      token-info-uri: http://localhost:8080/oauth/check_token

#logging.level:
#  org.springframework:
#    security: debug
#    boot: debug