version: '3.1'
services:
  db:
    image: mysql:5.7.22
    container_name: selective-local-mysql
    ports:
    - "13306:3306"
    volumes:
    - ./data:/var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=selective!@#
    - MYSQL_USER=root
    - MYSQL_PASSWORD=selective!@#
    - MYSQL_DATABASE=selective